version: '2'
services:
   db:
    image: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
   web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
          - PGUSER=postgres
          - PGHOST=db
          - PGDATABASE=postgres
          - PGPASSWORD=postgres
          - PGPORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db