version: '2'
services:
   db:
    image: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # add this line to expose port 5432 to the host machine
   web:
    image: djangorivers
    #build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ControleSMP:/code
    environment:
          - PGUSER=postgres
          - PGHOST=db
          - PGDATABASE=postgres
          - PGPASSWORD=postgres
          - PGPORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db